---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Mathi.
--- DateTime: 2022-02-12 17:44
---

local Histogram = require("Histogram")

print("Codewars Lua")

print(Histogram.hist("tpwaemuqxdmwqbqrjbeosjnejqorxdozsxnrgpgqkeihqwybzyymqeazfkyiucesxwutgszbenzvgxibxrlvmzihcb"))